### ISSUE TITLE
Default users cannot be found in page object yml

### ISSUE THREAD

**Issue by dougnoel** [dougnoel/sentinel#74]
This does not currently work, but if default is changed to demo, then the tests pass. We should use default if no specific env login is provided.
```
urls:
   base: http://newtours.demoaut.com/
accounts:
   default:
      RegularUser:
         username: test
         password: test
      BadUser:
         username: test
         password: test
```
